# Generated by Django 4.2.11 on 2024-03-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Estudante',
        ),
        migrations.RenameField(
            model_name='estudante',
            old_name='contact',
            new_name='contacto',
        ),
        migrations.RenameField(
            model_name='estudante',
            old_name='name',
            new_name='nome',
        ),
        migrations.AlterModelTable(
            name='estudante',
            table='Estudante',
        ),
    ]
